services:
  api:
    image: resume-template-api:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-template-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      MongoDB__ConnectionString: "mongodb://resume-parser-mongo:27017"
      MongoDB__DatabaseName: "resume_parser"
      MongoDB__CollectionName: "parsed_resumes"
    ports:
      - "8080:8080"
    volumes:
      - ./templates:/app/templates
    networks:
      - resume-parser-dev

networks:
  resume-parser-dev:
    external: true
